# Generated by Django 4.0.5 on 2022-06-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
    ]
