# Generated by Django 4.0.5 on 2022-06-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0002_alter_lecturer_confirm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='content',
        ),
    ]
