# Generated by Django 4.0.5 on 2022-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecturer', '0003_rename_description_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lecturer',
            field=models.BooleanField(default=False),
        ),
    ]
