# Generated by Django 4.0.3 on 2022-06-09 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=35, verbose_name='First Name')),
                ('Lname', models.CharField(max_length=35, verbose_name='Last Name')),
                ('date_registered', models.DateTimeField(default=datetime.datetime.now)),
                ('date_of_birth', models.DateField()),
                ('student_email', models.EmailField(max_length=254, verbose_name='Student Email')),
            ],
        ),
    ]
