# Generated by Django 4.0.3 on 2022-06-11 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Username',
            field=models.CharField(default=django.utils.timezone.now, max_length=35, verbose_name='User Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password1',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Password Again'),
            preserve_default=False,
        ),
    ]
