# Generated by Django 4.0.3 on 2022-06-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_username_student_password1_student_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='password1',
            new_name='password',
        ),
    ]
